import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Enhanced sidebar with better organization and features from 3.8+
  docSidebar: [
    'about',
    'getting-started',
    {
      type: 'category',
      label: '🔧 Service Registration',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'service-registration'},
      ],
    },
    {
      type: 'category',
      label: '⚙️ Service Invocation',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'service-invocation'},
      ],
    },
    {
      type: 'category',
      label: '🔄 Service Lifecycle',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'service-lifecycle'},
      ],
    },
    {
      type: 'category',
      label: '📦 Container Management',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'container'},
      ],
    },
    {
      type: 'category',
      label: '🚀 Migration & Upgrading',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'migrating'},
        {type: 'autogenerated', dirName: 'upgrading'},
      ],
    },
    {
      type: 'category',
      label: '🔍 Troubleshooting',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'troubleshooting'},
      ],
    },
    'glossary',
  ],
};

export default sidebars;
